### ISSUE TITLE
Honoring GPL by updating the repo to match the fi

### ISSUE THREAD

**Issue by InstantMuffin** [Sovol3d/Sv06-Source-Code#4]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Today you have released another build of your firmware for the SV06.
This repository here does not match the firmware build you offer to download. You don't mention anywhere on the download page of the new build on your website that the firmware is a derivative of the gpl-licensed marlin firmware, nor do you publish the source, nor do you comply with a written offer to supply the source code if asked for.

I would like this repository to be updated so you honor the GPL, ideally with a decent commit history so people know what was altered from the upstream repository.

I have incentivized heaps of people to buy the SV06 who have done so on my behalf and continue to offer support to them and numerous others on my own free time, and I find it hard to keep up giving decent advice in regards to firmware.
In between builds from Facebook groups that violated the GPL, to now current builds of that community firmware that reveal that previous builds have been compiled against the wrong MCU (thus posing a risk by creating undefined behavior) where no later warning and recommendation to update has been given by the author of the fork as far as I know, I would really love for just you as the vendor to have a decent, updated, and transparent repo of your hopefully working firmware so I can finally recommend a firmware to be used.

Thank you and best wishes

### Version of Marlin Firmware

No idea

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by jmfsanjurjo** [comment]
I also join that request. I completely agree with [instantmuffin](https://github.com/InstantMuffin) but I don't know if it should be put in "issues" or in "pull request"
Thanks a lot
